apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: kibana:7.17.5
          ports:
            - containerPort: 5601
          env:
            - name: elasticsearch.hosts
              value: "http://elasticsearch:9200"
            - name: elasticsearch.username
              value: "elastic"
            - name: elasticsearch.password
              value: "changeme"