apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash
  labels:
    app: logstash
data:
  logstash.yml: |
    path.config: /usr/share/logstash/pipeline
  logstash.conf: |
    input {
    	tcp {
    		port => 5000
    		codec => json
    	}
    }

    output {
    	elasticsearch {
    		hosts => "elasticsearch:9200"
    		user => "elastic"
    		password => "changeme"
    	}
    }