apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  labels:
    app: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - name: logstash
          image: logstash:7.17.5
          ports:
            - containerPort: 5044
            - containerPort: 5000
            - containerPort: 5000
              protocol: UDP
            - containerPort: 9600
          volumeMounts:
            - name: config
              mountPath: /usr/share/logstash/config
            - name: pipeline
              mountPath: /usr/share/logstash/pipeline
      volumes:
        - name: config
          configMap:
            name: logstash
            items:
              - key: logstash.yml
                path: logstash.yml
        - name: pipeline
          configMap:
            name: logstash
            items:
              - key: logstash.conf
                path: logstash.conf