apiVersion: v1
kind: Service
metadata:
  name: logstash
  labels:
    app: logstash
spec:
  selector:
    app: logstash
  ports:
    - name: "5044"
      port: 5044
      targetPort: 5044
    - name: "5000tcp"
      protocol: TCP
      port: 5000
      targetPort: 5000
    - name: "5000udp"
      protocol: UDP
      port: 5000
      targetPort: 5000
    - name: "9600"
      port: 9600
      targetPort: 9600